#!/usr/bin/env bash
#
# CyberShop — one-command local dev environment.
#
# Idempotent: safe to re-run any time (including after a full environment
# wipe). It will:
#   1. install dependencies if node_modules is missing
#   2. generate worker/.dev.vars (random dev secrets) if missing
#   3. generate web/.env.local (sharing the worker's INTERNAL_SECRET) if missing
#   4. apply D1 migrations (no-op when already applied)
#   5. optionally re-seed demo data (--seed)
#
# It does NOT start the servers. After this, run:
#   worker:  cd worker && npm run dev        → http://127.0.0.1:8787
#   web:     cd web && npm run dev           → http://localhost:3000
#
# Usage:  ./scripts/bootstrap-dev.sh [--seed]
set -euo pipefail
cd "$(dirname "$0")/.."

SEED=0
[ "${1:-}" = "--seed" ] && SEED=1

command -v openssl >/dev/null || { echo "error: openssl is required"; exit 1; }

# --- 1. dependencies ---------------------------------------------------------
if [ ! -d worker/node_modules ]; then
  echo "→ worker: installing dependencies…"
  (cd worker && npm ci --no-fund --no-audit)
else
  echo "✓ worker: dependencies present"
fi
if [ ! -d web/node_modules ]; then
  echo "→ web: installing dependencies…"
  (cd web && npm ci --no-fund --no-audit)
else
  echo "✓ web: dependencies present"
fi

# --- 2. worker env ------------------------------------------------------------
if [ ! -f worker/.dev.vars ]; then
  echo "→ generating worker/.dev.vars (random dev secrets)…"
  AUTH=$(openssl rand -hex 32)
  INT=$(openssl rand -hex 32)
  GW=$(openssl rand -hex 32)
  SALT=$(openssl rand -hex 16)
  cat > worker/.dev.vars <<EOF
# Generated by scripts/bootstrap-dev.sh — dev-only values.
AUTH_SECRET=$AUTH
INTERNAL_SECRET=$INT
GATEWAY_SECRET=$GW
APP_URL=http://localhost:3000
WEB_ORIGIN=http://localhost:3000
SESSION_SECURE=0
IP_SALT=$SALT
MEDIA_DRIVER=d1
MEDIA_BASE_URL=http://localhost:3000
GATEWAY_PUBLIC_URL=http://localhost:8081
PAYSTACK_MOCK=1
PAYSTACK_PUBLIC_KEY=pk_test_local
PAYSTACK_SECRET_KEY=sk_test_local
PAYSTACK_WEBHOOK_URL=http://localhost:8787/api/webhooks/paystack
# first-boot admin (worker/src/boot.ts creates it once)
SEED_ADMIN_EMAIL=admin@test.ng
SEED_ADMIN_PASSWORD=AdminPass123
EOF
else
  echo "✓ worker: .dev.vars present"
fi
INT=$(grep '^INTERNAL_SECRET=' worker/.dev.vars | cut -d= -f2)

# --- 3. web env ---------------------------------------------------------------
if [ ! -f web/.env.local ]; then
  echo "→ generating web/.env.local…"
  cat > web/.env.local <<EOF
WORKER_URL=http://127.0.0.1:8787
WORKER_INTERNAL_SECRET=$INT
SITE_URL=http://localhost:3000
EOF
else
  echo "✓ web: .env.local present"
fi

# --- 4. migrations -------------------------------------------------------------
echo "→ applying D1 migrations (local)…"
(cd worker && npm run --silent db:migrate >/dev/null)

# --- 5. demo data (optional) ----------------------------------------------------
if [ "$SEED" = "1" ]; then
  ./scripts/seed-demo.sh
fi

cat <<'EOF'

Done. Start the servers:

  cd worker && npm run dev      # API  → http://127.0.0.1:8787
  cd web && npm run dev         # web  → http://localhost:3000

Admin:   admin@test.ng / AdminPass123
EOF
[ "$SEED" = "1" ] && echo "Vendor:  cea@test.ng / Passw0rd123 (Cyber Elias Academy, Port Harcourt catalogue)"
